project:
  type: website
  output-dir: docs

website:
  title: "Mabvuto Yesaya"
  site-url: "https://m-yesaya.github.io/website/"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: posts/
        text: Blog


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true




